<%@ Page Language="C#" AutoEventWireup="true" CodeFile="updatemp.aspx.cs" Inherits="updatemp" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            height: 1126px;
        }
    </style>
</head>
<body>

    <form id="form1" runat="server">
    <div style=" text-align:right; ">
<asp:Button ID="ButtLog" runat="server" Text="Logout" BorderStyle="None" 
            PostBackUrl="~/AdminHome.aspx" /></div>
    <div align="center" 
        style="color:Olive;background-color:Aqua; font-family:Times New Roman; font-size:x-large; font-style:italic;" 
        class="style1">Employee Information
    
        <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            AutoGenerateRows="False" BackColor="White" BorderColor="#CC9966" 
            BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="EmployeeId" 
            DataSourceID="SqlDataSource1" Height="50px" Width="125px">
            <EditRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <Fields>
                <asp:BoundField DataField="EmployeeId" HeaderText="EmployeeId" ReadOnly="True" 
                    SortExpression="EmployeeId" />
                <asp:BoundField DataField="SSN" HeaderText="SSN" SortExpression="SSN" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="sex" HeaderText="sex" SortExpression="sex" />
                <asp:BoundField DataField="Job_Title" HeaderText="Job_Title" 
                    SortExpression="Job_Title" />
                <asp:BoundField DataField="JoinDate" HeaderText="JoinDate" 
                    SortExpression="JoinDate" />
                <asp:BoundField DataField="Cur_Salary" HeaderText="Cur_Salary" 
                    SortExpression="Cur_Salary" />
                <asp:BoundField DataField="UserName" HeaderText="UserName" 
                    SortExpression="UserName" />
                <asp:BoundField DataField="Password" HeaderText="Password" 
                    SortExpression="Password" />
                <asp:BoundField DataField="Annual_Salary" HeaderText="Annual_Salary" 
                    SortExpression="Annual_Salary" />
            </Fields>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
        </asp:DetailsView>
       
        <br />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:Retail_ChainDbConnectionString %>" 
            SelectCommand="SELECT * FROM [Employee]" UpdateCommand="update Employee set [SSN]=@SSN,[name]=@name,[sex]=@sex,[Job_Title]=@Job_Title,[JoinDate]=@JoinDate,[Cur_Salary]=@Cur_Salary,[Annual_Salary]=@Annual_Salary where [EmployeeId]=@EmployeeId " DeleteCommand="delete from Employee where [EmployeeId]=@EmployeeId">
            <UpdateParameters>
            <asp:Parameter Name="SSN" />
            <asp:Parameter Name="name" />
            <asp:Parameter Name="sex" />
            <asp:Parameter Name="Job_Title" />
            <asp:Parameter Name="JoinDate" />
            <asp:Parameter  Name="Cur_Salary"/>
            <asp:Parameter Name="Annual_Salary" />
            </UpdateParameters>
            <DeleteParameters>
            <asp:Parameter Name="EmployeeId"/>
            </DeleteParameters>
            
            </asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
